version: '2.2'

services:
  ppomppu:
    build: .
    image: ppomppu:latest
    container_name: ppomppu
    privileged: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./src:/home/webadmin/ppomppu
      - ./configs:/etc/httpd/conf.d:ro
      - ./configs/php.ini:/etc/php.ini:ro
      - ./configs/nutcracker.yml:/etc/nutcracker/nutcracker.yml:ro
    networks:
      default:
        ipv4_address: 192.168.80.2
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.80.0/24
